### ISSUE TITLE
Possibly leaked handle?

### ISSUE THREAD

**Issue by acepace** [ForbesLindesay/sync-request#129]
Running tests using sync-request and Jest has Jest detecting a possibly leaked handle.

```
PROCESSWRAP

      at start (node_modules/sync-rpc/lib/index.js:33:13)
      at sendMessage (node_modules/sync-rpc/lib/index.js:133:17)
      at createClient (node_modules/sync-rpc/lib/index.js:173:27)
      at Object.<anonymous> (node_modules/sync-request/lib/index.js:16:14)
```

**Comment by prateeksha23** [comment]
I am also facing the same issue. Is there any update?

**Comment by nktnet1** [comment]
Had a similar problem with Jest so I wrote a library called [sync-request-curl](https://github.com/nktnet1/sync-request-curl).

The usage is the same.

[sync-request-curl](https://github.com/nktnet1/sync-request-curl) is free from this bug and has better performances from leveraging [node-libcurl](https://github.com/JCMais/node-libcurl), but doesn't have close to the same level of compatibility as [sync-request](https://github.com/ForbesLindesay/sync-request). It only works with recent versions of NodeJS and has no support for JavaScript in the Browser.

I believe this issue is also closely linked with #137.

The cause is sync-rpc and is explained in issue 10:
- https://github.com/ForbesLindesay/sync-rpc/issues/10
