### ISSUE TITLE
certificate has expired

### ISSUE THREAD

**Issue by lijenx** [ForbesLindesay/sync-request#24]
I'm trying to use sync-request to get rest api resources from a custom-build embedded device. This device's http server uses ssl/https with an expired certificate. For reasons that are both complicated and boring we're not going to bother trying to update the certificate.

Is there some way to configure sync-request to ignore expired certificates? Something like curl's -k option or wget's --no-check-certificate option?

**Comment by lijenx** [comment]
SOLVED: NodeJS will ignore the host's expired certificate if you include this line at the top of your file:

    process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';

**Comment by Thalinda** [comment]
is this approach safe to implement in the log there is a even warning not to use it this way did you found any other way

**Comment by ForbesLindesay** [comment]
@Thalinda the right approach is to fix the server you want to talk to so that it has a valid, not-expired certificate. Otherwise you might as well just use http. To benefit from https security, you need to verify certificates. The other problem with this approach is that it disables certificate checks for all requests, not just the request that is failing.
