### ISSUE TITLE
sync-request is making code run too slow

### ISSUE THREAD

**Issue by ximrx** [ForbesLindesay/sync-request#4]
While running sync-request for scrapping web pages in 'for' loop, it is taking hell lot of time for each iteration/request. If I use default async request socket hangs up.
At start of execution sync-request consoles "native module could not be found so busy waiting will be used for spwan-sync"

**Comment by ForbesLindesay** [comment]
sync-request is not intended to be performant.  It is especially slow when running in old versions of node.js on windows or on environments without support for native modules.

Unfortunately this slowness cannot be fixed.  Instead you should use async requests.  These even allow you to make slow requests faster by running them in parallel.

I suggest posting your async attempt on stack overflow and asking why it doesn't work.  If nobody gives you a decent answer, feel free to post a link here and I'll take a look.

**Comment by NameFILIP** [comment]
I've tried another module (https://github.com/dhruvbird/http-sync) and it is 10 times faster..

**Comment by ForbesLindesay** [comment]
That's probably because that library is using libcurl internally, so it doesn't pay the cost of setting up an extra cost of starting up a second node.js process.  The issue with that approach is that it's much harder to maintain exactly identical behaviour across platform (try getting http-sync to work on Windows) and near impossible to get it to behave exactly the same as async requests in node.js.  Because this library uses then-request, it has a perfectly consistent API.

**Comment by nktnet1** [comment]
I wrote [sync-request-curl](https://github.com/nktnet1/sync-request-curl) as a proof of concept which currently supports a subset of the features from sync-request, and runs quite quickly (uses [node-libcurl](https://github.com/JCMais/node-libcurl)).

Won't work in browsers and may not have the same level of compatibility, but for people looking for a fast way to send synchronous requests in NodeJS, hopefully, this would suffice :).
