### ISSUE TITLE
Blocks Node Process

### ISSUE THREAD

**Issue by sudhir-jabong** [ForbesLindesay/sync-request#55]
While using Sync Request for uploading CSV files, blocks the process. Is anything can be done to solve this ?

**Comment by ForbesLindesay** [comment]
The whole reason why web requests (and IO in general) is async in node.js (and frontend JavaScript for that matter) is that making synchronous requests would block the process.  There is no way round that, it's a fundamental constraint of single threaded languages.

What you can (should) do is use [then-request](https://github.com/then/then-request) which is asynchronous.  It has the exact same API as sync-request except that requests return Promises rather than directly returning values.

I've tried to make this as clear as I can in the README.
