### ISSUE TITLE
Process hangs forever since 4.0.2

### ISSUE THREAD

**Issue by ooflorent** [ForbesLindesay/sync-request#74]
The change introduced in 65fcf25a0c603d64fc810465ff296118ba40427e has locked our deploy server. In 4.0.1 we add the below warning but everything was fine:

```
Could not use "nc", falling back to slower node.js method for sync requests.
```

Since 4.0.2, the process hangs forever. Downgrading to 4.0.1 solves the issue.

**Comment by ForbesLindesay** [comment]
This probably means you have a netcat command that is somehow misbehaving.  If you can figure out a fix, I'm happy to accept pull requests, but as it stands I don't have enough info.

**Comment by blutorange** [comment]
I had the same problem.  I took a look and (at least in my case) the problem was that netcat keeps the connection open indefinitely, waiting for a response from the nc-server, while the nc-server keeps listening for data from the client indefinitely, never sending a response.

In nc-server, instead of piping, I listened to the `data` event until the client sends a \r\r\n to signal that it is done sending.

https://github.com/blutorange/sync-request/commit/505257a742f025beedb0cef2447ae05160fc585b

**Comment by ooflorent** [comment]
Thanks 👍

**Comment by ForbesLindesay** [comment]
Let me know if it's still broken :)

**Comment by evromalarkey** [comment]
Is it fixed? I've just installed [nc](https://www.npmjs.com/package/nc) globally to suppress the warning message, but now it hangs forever for me. Tested on node.js version 8.9.3 LTS
